document.addEventListener("DOMContentLoaded", () => {
  const SUPABASE_URL = "https://mbmuextzyyhseibruaop.supabase.co";
  const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ibXVleHR6eXloc2VpYnJ1YW9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY4NTUxNzMsImV4cCI6MjA5MjQzMTE3M30.F6iclxio0NijUmp5pTYgNlMElg42J6fbai0XJEdnQoM";
  const SUPABASE_BUCKET = "gallery-uploads";
  const SUPABASE_TABLE = "gallery_posts";
  const supabaseClient = window.supabase?.createClient ? window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null;

  const THEMES = [
    { key: "愛情紀念", icon: "fa-regular fa-heart", subs: ["情侶名字", "交往紀念日", "結婚周年", "情話短句", "求婚日期", "英文縮寫", "專屬暗號", "初次見面日"] },
    { key: "家人親情", icon: "fa-solid fa-people-group", subs: ["爸媽名字", "孩子名字", "出生日期", "家庭座右銘", "感謝爸媽", "兄弟姐妹", "阿公阿嬤紀念", "親子專屬字句"] },
    { key: "寵物回憶", icon: "fa-solid fa-paw", subs: ["毛孩名字", "腳印圖案", "寵物生日", "到家紀念日", "寵物剪影", "陪伴語錄", "貓狗插畫", "離世紀念"] },
    { key: "心靈寄託", icon: "fa-solid fa-leaf", subs: ["宗教信仰", "平安祝福", "正能量語錄", "重新開始", "思念陪伴", "阿彌陀佛", "God Bless You", "媽祖保佑"] },
    { key: "個人簽名", icon: "fa-solid fa-pen-nib", subs: ["英文名字", "中文名字", "簽名款式", "姓名縮寫", "暱稱 / 代號", "個性文字", "草寫簽名", "專屬符號"] },
    { key: "生日節慶", icon: "fa-solid fa-cake-candles", subs: ["生日快樂", "生日紀念", "18歲成年禮", "畢業紀念", "母親節", "父親節", "聖誕節", "退休紀念"] },
    { key: "企業團體", icon: "fa-regular fa-building", subs: ["公司 Logo", "品牌名稱", "團隊名稱", "社團紀念", "車隊圖案", "扶輪社", "獅子會", "活動紀念"] },
    { key: "開運祝福", icon: "fa-solid fa-wand-magic-sparkles", subs: ["招財進寶", "平安順利", "財源廣進", "健康平安", "考運亨通", "好運連連", "一路發", "福氣滿滿"] },
    { key: "客製圖案", icon: "fa-regular fa-image", subs: ["愛心圖案", "星座符號", "月亮星星", "簡約線條", "生肖圖案", "自備圖稿", "品牌圖騰", "插畫圖案"] },
    { key: "全部", icon: "fa-solid fa-border-all", subs: ["全部分享"] }
  ];

  const DEMO_POSTS = [
    { title: "我們的 5 週年紀念日", topic: "愛情紀念", subtopic: "交往紀念日", carrier: "鏡片", customer_name: "小雨", story: "把兩個人的紀念日刻在眼鏡角落，每天都能想起那一天。", image_urls: ["images/lens-01.jpg", "images/frame-01.jpg", "images/cloth-01.jpg"], created_at: "2026-04-26T10:00:00+08:00", likes: 126 },
    { title: "專屬於我的簽名", topic: "個人簽名", subtopic: "英文名字", carrier: "鏡片", customer_name: "Bruce", story: "英文簽名很低調，但戴上後很有自己的風格。", image_urls: ["images/frame-01.jpg", "images/lens-01.jpg", "images/box-01.jpg"], created_at: "2026-04-25T12:00:00+08:00", likes: 98 },
    { title: "我家 Cooper", topic: "寵物回憶", subtopic: "毛孩名字", carrier: "鏡片", customer_name: "Wen", story: "把毛孩名字刻在眼鏡上，像牠每天都陪著我看世界。", image_urls: ["images/lens-01.jpg", "images/box-01.jpg", "images/frame-01.jpg"], created_at: "2026-04-24T15:20:00+08:00", likes: 88 },
    { title: "永遠相信自己", topic: "心靈寄託", subtopic: "正能量語錄", carrier: "鏡片", customer_name: "Wayne", story: "Keep Going 是每天提醒自己的小力量。", image_urls: ["images/lens-01.jpg", "images/cloth-01.jpg", "images/box-01.jpg"], created_at: "2026-04-23T09:00:00+08:00", likes: 77 },
    { title: "ABC 企業團隊紀念", topic: "企業團體", subtopic: "公司 Logo", carrier: "眼鏡盒", customer_name: "ABC 團隊", story: "公司活動紀念款，低調但很有團隊識別。", image_urls: ["images/box-01.jpg", "images/lens-01.jpg", "images/frame-01.jpg"], created_at: "2026-04-22T11:00:00+08:00", likes: 76 },
    { title: "願一切平安順利", topic: "開運祝福", subtopic: "平安順利", carrier: "鏡片", customer_name: "小美", story: "簡單一句平安喜樂，送給每天努力的自己。", image_urls: ["images/lens-01.jpg", "images/cloth-01.jpg", "images/box-01.jpg"], created_at: "2026-04-21T19:00:00+08:00", likes: 64 }
  ];

  const state = { topic: "全部", subtopic: "", keyword: "", posts: [], selectedSlot: null, draggedSlot: null, images: [null, null, null], files: [null, null, null], isPreviewMode: false };
  const $ = s => document.querySelector(s);
  const $$ = s => Array.from(document.querySelectorAll(s));

  const galleryGrid = $("#galleryGrid"), resultMeta = $("#resultMeta"), desktopTopicFilter = $("#desktopTopicFilter"), desktopSearchInput = $("#desktopSearchInput"), sortSelect = $("#sortSelect"), hotChipScroll = $("#hotChipScroll"), subFilterRow = $("#subFilterRow"), subChipScroll = $("#subChipScroll"), clearSubFilter = $("#clearSubFilter");
  const themeModal = $("#themeModal"), themeGrid = $("#themeGrid"), openThemeModalBtn = $("#openThemeModal"), closeThemeModalBtn = $("#closeThemeModal");
  const detailModal = $("#detailModal"), closeDetail = $("#closeDetail"), detailBody = $("#detailBody");
  const uploadModal = $("#uploadModal"), openUploadBtns = $$(".js-open-upload"), closeUpload = $("#closeUpload"), fileInput = $("#fileInput"), uploadBoxes = $$(".upload-box"), workTitle = $("#workTitle"), workTitleError = $("#workTitleError"), workCategory = $("#workCategory"), carrierCategory = $("#carrierCategory"), shareText = $("#shareText"), currentChar = $("#currentChar"), previewBtn = $("#previewBtn"), submitBtn = $("#submitBtn"), toast = $("#toast");
  const cropModal = $("#cropModal"), cropImage = $("#cropImage"), applyCrop = $("#applyCrop"), cancelCrop = $("#cancelCrop"), closeCrop = $("#closeCrop");
  let cropper = null, cropTargetSlot = null;

  init();

  function init() { populateCategorySelect(); renderThemeModal(); bindEvents(); loadPostsFromSupabase(); applyOpenUploadFromUrl(); }
  function populateCategorySelect() { workCategory.innerHTML = THEMES.filter(t => t.key !== "全部").map(t => `<option value="${t.key}">${t.key}</option>`).join(""); }
  function renderThemeModal() { themeGrid.innerHTML = THEMES.map(t => { const count = t.key === "全部" ? 236 : 18 + Math.floor(Math.random() * 18); return `<article class="theme-card" data-topic="${t.key}"><div class="theme-card-head" role="button" tabindex="0"><div class="theme-icon"><i class="${t.icon}"></i></div><h3 class="theme-card-title">${t.key === "全部" ? "全部主題" : t.key}</h3><span class="theme-count">${count}</span></div><ul class="theme-sub-list">${t.subs.slice(0, 5).map(s => `<li><button type="button" data-topic="${t.key}" data-subtopic="${s}">• ${s}</button></li>`).join("")}</ul><button type="button" class="theme-card-action" data-topic="${t.key}">查看全部</button></article>`; }).join(""); }

  function bindEvents() {
    desktopTopicFilter.addEventListener("change", () => setTopic(desktopTopicFilter.value));
    desktopSearchInput.addEventListener("input", () => { state.keyword = desktopSearchInput.value.trim(); renderPosts(); });
    sortSelect.addEventListener("change", renderPosts);
    hotChipScroll.addEventListener("click", e => { const chip = e.target.closest(".topic-chip"); if (!chip || chip.id === "openThemeModal") return; setTopic(chip.dataset.topic || "全部"); });
    clearSubFilter.addEventListener("click", () => { state.subtopic = ""; renderSubChips(); renderPosts(); });
    subChipScroll.addEventListener("click", e => { const chip = e.target.closest(".sub-chip"); if (!chip) return; state.subtopic = chip.dataset.subtopic || ""; renderSubChips(); renderPosts(); });
    openThemeModalBtn.addEventListener("click", openThemeModal); closeThemeModalBtn.addEventListener("click", closeThemeModal);
    themeModal.addEventListener("click", e => { if (e.target === themeModal) closeThemeModal(); const sub = e.target.closest("[data-subtopic]"); if (sub) { setTopic(sub.dataset.topic, sub.dataset.subtopic); closeThemeModal(); } const action = e.target.closest(".theme-card-action,.theme-apply-all"); if (action) { setTopic(action.dataset.topic || "全部"); closeThemeModal(); } const head = e.target.closest(".theme-card-head"); if (head && window.innerWidth <= 768) head.closest(".theme-card").classList.toggle("is-open"); });
    galleryGrid.addEventListener("click", e => { const card = e.target.closest(".gallery-card"); if (!card) return; e.preventDefault(); openDetailModal(card); });
    closeDetail.addEventListener("click", closeDetailModal); detailModal.addEventListener("click", e => { if (e.target === detailModal) closeDetailModal(); });
    openUploadBtns.forEach(btn => btn.addEventListener("click", () => { const member = JSON.parse(localStorage.getItem("lohasMember") || "null"); if (!member || !member.erpid) { localStorage.setItem("redirectAfterLogin", "gallery02.html?openUpload=1"); window.location.href = "login.html"; return; } openUploadModal(); }));
    closeUpload.addEventListener("click", closeUploadModal); uploadModal.addEventListener("click", e => { if (e.target === uploadModal) closeUploadModal(); });
    fileInput.addEventListener("change", e => { const file = e.target.files[0]; if (state.selectedSlot !== null) readImageFile(file, state.selectedSlot); });
    uploadBoxes.forEach(box => bindUploadBox(box));
    shareText.addEventListener("input", () => currentChar.textContent = shareText.value.length);
    workTitle.addEventListener("input", () => workTitleError.textContent = "");
    previewBtn.addEventListener("click", () => { if (!validateForm()) return; openPreviewDetail(); });
    submitBtn.addEventListener("click", submitPost);
    applyCrop.addEventListener("click", applyCropToSlot); cancelCrop.addEventListener("click", closeCropModal); closeCrop.addEventListener("click", closeCropModal);
  }

  async function loadPostsFromSupabase() { state.posts = [...DEMO_POSTS]; if (!supabaseClient) return renderPosts(); try { const { data, error } = await supabaseClient.from(SUPABASE_TABLE).select("id,title,topic,subtopic,carrier,story,customer_name,member_id,image_urls,main_image_url,created_at,is_public").eq("is_public", true).order("created_at", { ascending: false }); if (error) throw error; state.posts = [...(data || []), ...DEMO_POSTS]; } catch (err) { console.error(err); showToast("讀取分享失敗，先顯示示範內容"); } renderPosts(); }
  function setTopic(topic = "全部", subtopic = "") { state.topic = topic || "全部"; state.subtopic = subtopic || ""; desktopTopicFilter.value = state.topic; $$(".topic-chip").forEach(c => c.classList.toggle("active", c.dataset.topic === state.topic)); renderSubChips(); renderPosts(); }
  function renderSubChips() { const theme = THEMES.find(t => t.key === state.topic); if (!theme || state.topic === "全部") { subFilterRow.hidden = true; subChipScroll.innerHTML = ""; return; } subFilterRow.hidden = false; subChipScroll.innerHTML = theme.subs.map(s => `<button type="button" class="sub-chip ${state.subtopic === s ? "active" : ""}" data-subtopic="${s}">${s}</button>`).join(""); }
  function getFilteredPosts() { const kw = state.keyword.toLowerCase(); let posts = state.posts.filter(p => { const text = [p.title,p.topic,p.subtopic,p.carrier,p.customer_name,p.story].join(" ").toLowerCase(); return (state.topic === "全部" || p.topic === state.topic) && (!state.subtopic || p.subtopic === state.subtopic) && (!kw || text.includes(kw)); }); if (sortSelect.value === "popular") posts = posts.sort((a,b) => (b.likes || 0) - (a.likes || 0)); return posts; }
  function renderPosts() { const posts = getFilteredPosts(); galleryGrid.innerHTML = posts.map(cardTemplate).join(""); resultMeta.textContent = `共 ${posts.length} 筆分享`; }
  function cardTemplate(p) { const img = p.image_urls?.[0] || p.main_image_url || "images/lens-01.jpg"; const name = maskName(p.customer_name || "顧客"); const imgs = (p.image_urls || [img]).join(","); return `<a href="#" class="gallery-card" data-topic="${esc(p.topic)}" data-subtopic="${esc(p.subtopic)}" data-carrier="${esc(p.carrier)}" data-name="${esc(name)}" data-story="${esc(p.story)}" data-images="${esc(imgs)}"><div class="img-box"><img src="${img}" alt="${esc(p.title || "刻圖分享")}"><span class="card-like"><i class="fa-regular fa-heart"></i></span></div><div class="card-info"><div class="card-tags"><span class="card-tag">${p.topic || "靈感主題"}</span>${p.subtopic ? `<span class="card-tag">${p.subtopic}</span>` : ""}</div><h3 class="card-title">${p.title || "未命名分享"}</h3><div class="card-meta"><span><i class="fa-regular fa-user"></i>${name}</span><span><i class="fa-regular fa-clock"></i>${timeAgo(p.created_at)}</span></div></div></a>`; }
  function openThemeModal(){ themeModal.classList.add("is-open"); themeModal.setAttribute("aria-hidden","false"); document.body.style.overflow="hidden"; }
  function closeThemeModal(){ themeModal.classList.remove("is-open"); themeModal.setAttribute("aria-hidden","true"); document.body.style.overflow=""; }
  function openDetailModal(card){ const imgs=(card.dataset.images||"").split(",").map(s=>s.trim()).filter(Boolean); const title=card.querySelector(".card-title")?.textContent||"未命名分享"; detailBody.innerHTML=`<div class="detail-gallery"><div class="detail-main-image"><img src="${imgs[0]||"images/lens-01.jpg"}" alt="${esc(title)}"></div><div class="detail-sub-list">${imgs.slice(1,3).map(src=>`<div class="detail-sub-image"><img src="${src}" alt="${esc(title)}"></div>`).join("")}</div></div><div class="detail-title-row"><h3 class="detail-title">${title}</h3><span class="detail-user">${card.dataset.name||"顧客"}</span></div><div class="detail-meta"><span class="detail-chip">${card.dataset.topic||"靈感主題"}</span>${card.dataset.subtopic?`<span class="detail-chip">${card.dataset.subtopic}</span>`:""}<span class="detail-chip">${card.dataset.carrier||"刻圖位置"}</span></div><p class="detail-story">${card.dataset.story||"這是一份來自顧客分享的刻圖照片。"}</p>`; detailModal.classList.add("is-open"); detailModal.setAttribute("aria-hidden","false"); document.body.style.overflow="hidden"; }
  function closeDetailModal(){ detailModal.classList.remove("is-open"); detailModal.setAttribute("aria-hidden","true"); if(state.isPreviewMode){ uploadModal.classList.add("is-open"); uploadModal.setAttribute("aria-hidden","false"); state.isPreviewMode=false; document.body.style.overflow="hidden"; } else document.body.style.overflow=""; }
  function openUploadModal(){ uploadModal.classList.add("is-open"); uploadModal.setAttribute("aria-hidden","false"); document.body.style.overflow="hidden"; }
  function closeUploadModal(){ uploadModal.classList.remove("is-open"); uploadModal.setAttribute("aria-hidden","true"); document.body.style.overflow=""; }
  function validateForm(){ workTitleError.textContent=""; if(!getMainImage()){ showToast("請至少上傳一張首圖"); return false; } if(!workTitle.value.trim()){ workTitleError.textContent="請輸入分享名稱"; workTitle.focus(); return false; } return true; }
  function openPreviewDetail(){ const member=JSON.parse(localStorage.getItem("lohasMember")||"null"); const name=maskName(member?.name||"顧客"); const imgs=state.images.filter(Boolean); detailBody.innerHTML=`<div class="detail-gallery"><div class="detail-main-image"><img src="${imgs[0]}" alt="${esc(getTitle())}"></div><div class="detail-sub-list">${imgs.slice(1,3).map(src=>`<div class="detail-sub-image"><img src="${src}" alt="${esc(getTitle())}"></div>`).join("")}</div></div><div class="detail-title-row"><h3 class="detail-title">${getTitle()}</h3><span class="detail-user">${name}</span></div><div class="detail-meta"><span class="detail-chip">${workCategory.value}</span><span class="detail-chip">${carrierCategory.value}</span></div><p class="detail-story">${shareText.value.trim()||"這是一份來自顧客分享的刻圖照片。"}</p>`; state.isPreviewMode=true; uploadModal.classList.remove("is-open"); detailModal.classList.add("is-open"); }
  async function submitPost(){ if(!validateForm()) return; try{ submitBtn.disabled=true; submitBtn.textContent="上傳中..."; const newPost=await submitPostToSupabase(); state.posts.unshift(newPost); closeUploadModal(); clearForm(); renderPosts(); showToast("你的分享已成功送出"); } catch(err){ console.error(err); showToast(err.message||"上傳失敗，請檢查 Supabase 權限設定"); } finally{ submitBtn.disabled=false; submitBtn.textContent="送出分享"; } }
  async function submitPostToSupabase(){ if(!supabaseClient) throw new Error("Supabase 尚未載入"); const member=JSON.parse(localStorage.getItem("lohasMember")||"null"); if(!member||!member.erpid) throw new Error("請先登入會員後再分享照片"); const imageUrls=await uploadImagesToSupabase(); const postPayload={title:getTitle(),topic:workCategory.value,subtopic:"",carrier:carrierCategory.value,story:shareText.value.trim(),customer_name:member.name||"顧客",member_id:member.erpid,image_urls:imageUrls,main_image_url:imageUrls[0],is_public:true}; const {data,error}=await supabaseClient.from(SUPABASE_TABLE).insert(postPayload).select("id,title,topic,subtopic,carrier,story,customer_name,member_id,image_urls,main_image_url,created_at,is_public").single(); if(error) throw error; return data; }
  async function uploadImagesToSupabase(){ const urls=[]; for(const file of state.files.filter(Boolean)){ const ext=file.name.split(".").pop()?.toLowerCase()||"jpg"; const path=`public/${Date.now()}-${crypto.randomUUID()}.${ext}`; const {error}=await supabaseClient.storage.from(SUPABASE_BUCKET).upload(path,file,{cacheControl:"3600",upsert:false}); if(error) throw error; const {data}=supabaseClient.storage.from(SUPABASE_BUCKET).getPublicUrl(path); urls.push(data.publicUrl); } return urls; }
  function bindUploadBox(box){ const slot=Number(box.dataset.slot); resetBox(slot); box.addEventListener("click",e=>{ const del=e.target.closest("[data-delete-slot]"); if(del){ e.stopPropagation(); const s=Number(del.dataset.deleteSlot); state.files[s]=null; state.images[s]=null; renderBox(s); return; } openFilePicker(slot); }); box.addEventListener("dragover",e=>{ e.preventDefault(); box.classList.add("drag-enter"); }); box.addEventListener("dragleave",()=>box.classList.remove("drag-enter")); box.addEventListener("drop",e=>{ e.preventDefault(); $$(".upload-box").forEach(i=>i.classList.remove("dragging","drag-enter")); const file=e.dataTransfer.files[0]; if(file){ readImageFile(file,slot); return; } if(state.draggedSlot!==null&&state.draggedSlot!==slot) swapImages(state.draggedSlot,slot); }); box.addEventListener("dragstart",e=>{ if(!state.images[slot]){ e.preventDefault(); return; } state.draggedSlot=slot; box.classList.add("dragging"); }); box.addEventListener("dragend",()=>{ state.draggedSlot=null; $$(".upload-box").forEach(i=>i.classList.remove("dragging","drag-enter")); }); }
  function readImageFile(file,slot){ if(!file) return; if(!file.type.startsWith("image/")){ showToast("請上傳圖片格式"); return; } cropTargetSlot=slot; const reader=new FileReader(); reader.onload=e=>{ cropImage.src=e.target.result; cropModal.classList.add("is-open"); if(cropper) cropper.destroy(); cropper=new Cropper(cropImage,{aspectRatio:1,viewMode:1,dragMode:"move",autoCropArea:1,responsive:true,background:false,movable:true,zoomable:true,scalable:false,rotatable:false}); }; reader.readAsDataURL(file); }
  function applyCropToSlot(){ if(!cropper||cropTargetSlot===null) return; const canvas=cropper.getCroppedCanvas({width:1200,height:1200,imageSmoothingQuality:"high"}); const base64=canvas.toDataURL("image/jpeg",.9); state.images[cropTargetSlot]=base64; state.files[cropTargetSlot]=base64ToFile(base64,`gallery_${Date.now()}_${cropTargetSlot}.jpg`); renderBox(cropTargetSlot); closeCropModal(); }
  function closeCropModal(){ cropModal.classList.remove("is-open"); if(cropper) cropper.destroy(); cropper=null; cropTargetSlot=null; }
  function openFilePicker(slot){ state.selectedSlot=Number(slot); fileInput.value=""; fileInput.click(); }
  function resetBox(slot){ const box=document.querySelector(`.upload-box[data-slot="${slot}"]`); const isMain=box.classList.contains("main-upload"); box.classList.remove("has-image"); box.setAttribute("draggable","false"); box.innerHTML=`${isMain?'<span class="badge-main">首圖</span>':""}<div class="upload-placeholder"><i class="fa-regular fa-image"></i><p>新增圖片</p><span>${isMain?"點擊選擇，或拖曳圖片到這裡":"副圖"}</span></div>`; }
  function renderBox(slot){ const box=document.querySelector(`.upload-box[data-slot="${slot}"]`); const image=state.images[slot]; if(!image){ resetBox(slot); return; } const isMain=box.classList.contains("main-upload"); box.classList.add("has-image"); box.setAttribute("draggable","true"); box.innerHTML=`${isMain?'<span class="badge-main">首圖</span>':""}<img class="preview-image" src="${image}" alt="上傳預覽圖片"><button class="delete-btn" type="button" data-delete-slot="${slot}" aria-label="刪除圖片"><i class="fa-solid fa-xmark"></i></button>`; }
  function swapImages(a,b){ [state.images[a],state.images[b]]=[state.images[b],state.images[a]]; [state.files[a],state.files[b]]=[state.files[b],state.files[a]]; renderBox(a); renderBox(b); }
  function clearForm(){ state.images=[null,null,null]; state.files=[null,null,null]; uploadBoxes.forEach(box=>resetBox(Number(box.dataset.slot))); workTitle.value=""; workTitleError.textContent=""; shareText.value=""; currentChar.textContent="0"; workCategory.selectedIndex=0; carrierCategory.selectedIndex=0; }
  function applyOpenUploadFromUrl(){ const params=new URLSearchParams(window.location.search); if(params.get("openUpload")!=="1") return; const member=JSON.parse(localStorage.getItem("lohasMember")||"null"); if(member&&member.erpid){ openUploadModal(); window.history.replaceState({},document.title,window.location.pathname); } }
  function getMainImage(){ return state.images[0]; } function getTitle(){ return workTitle.value.trim()||"未命名分享"; }
  function maskName(name){ const n=(name||"顧客").trim(); if(n.length<=1) return `${n}＊`; const suffix=n.includes("先生")?"生":n.includes("小姐")?"姐":n.slice(-1); return `${n.slice(0,1)}＊${suffix}`; }
  function timeAgo(dateString){ if(!dateString) return "剛剛分享"; const diff=Math.max(0,new Date()-new Date(dateString)),m=60000,h=60*m,d=24*h; if(diff<m) return "剛剛分享"; if(diff<h) return `${Math.floor(diff/m)}分鐘前分享`; if(diff<d) return `${Math.floor(diff/h)}小時前分享`; if(diff<2*d) return "昨天分享"; return `${Math.floor(diff/d)}天前分享`; }
  function base64ToFile(base64,filename){ const arr=base64.split(","),mime=arr[0].match(/:(.*?);/)[1],bin=atob(arr[1]),bytes=new Uint8Array(bin.length); for(let i=0;i<bin.length;i++) bytes[i]=bin.charCodeAt(i); return new File([bytes],filename,{type:mime}); }
  function esc(v){ return String(v||"").replaceAll("&","&amp;").replaceAll('"',"&quot;").replaceAll("<","&lt;").replaceAll(">","&gt;"); }
  function showToast(message){ toast.textContent=message; toast.classList.add("is-show"); clearTimeout(showToast.timer); showToast.timer=setTimeout(()=>toast.classList.remove("is-show"),1800); }
});
